# Generated by Django 6.0.4 on 2026-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_transaction_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_uuid',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery')], max_length=200),
        ),
    ]
