# Generated by Django 6.0.4 on 2026-04-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_alter_products_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
